version: "3"
services:
  backend:
    container_name: backend
    image: sabirmostofa/spring-backend:latest
    build:
      context: ./backend
    ports:
      - "8090:8090"
    depends_on:
      - postgres
  frontend:
    container_name: frontend
    image: sabirmostofa/react_frontend:latest
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: chatbox
      POSTGRES_PASSWORD: chatbox
      POSTGRES_DB: chatbox
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  pgdata:
